// Code generated by "stringer -type Type"; DO NOT EDIT.

package scan

import "strconv"

const _Type_name = "EOFErrorPunctuatorIdentifierLeftParenLeftBrackLeftBraceRightParenRightBrackRightBraceCommaDotQuestionColonTildeStarSlashSemicolonGreaterOrEqualFixnumFlonumString"

var _Type_index = [...]uint8{0, 3, 8, 18, 28, 37, 46, 55, 65, 75, 85, 90, 93, 101, 106, 111, 115, 120, 129, 143, 149, 155, 161}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
